# Generated by Django 4.2 on 2026-03-30 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Emotion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("slug", models.SlugField(unique=True)),
                ("color", models.CharField(default="#6c757d", max_length=7)),
                ("icon", models.CharField(blank=True, max_length=10)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
    ]
