# Generated by Django 4.2 on 2026-03-30 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MediaItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tmdb_id", models.IntegerField(unique=True)),
                (
                    "media_type",
                    models.CharField(
                        choices=[("film", "Film"), ("tv", "TV Show")], max_length=4
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("year", models.IntegerField(blank=True, null=True)),
                ("poster_path", models.CharField(blank=True, max_length=255)),
                ("backdrop_path", models.CharField(blank=True, max_length=255)),
                ("overview", models.TextField(blank=True)),
                ("genres", models.JSONField(default=list)),
                ("runtime", models.IntegerField(blank=True, null=True)),
                ("tmdb_rating", models.FloatField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
